// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NBhsxDpQJl7yyK6f5f8jFIWIFiVO7SA',
    appId: '1:317504441577:web:85578520897f5a44027478',
    messagingSenderId: '317504441577',
    projectId: 'ihsan-tech-18a27',
    authDomain: 'ihsan-tech-18a27.firebaseapp.com',
    storageBucket: 'ihsan-tech-18a27.appspot.com',
    measurementId: 'G-ZNFDBBVB95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoqzXumcZG_QPxlNQoPK2wqPzYNn85jc',
    appId: '1:317504441577:android:38ed95746968e52c027478',
    messagingSenderId: '317504441577',
    projectId: 'ihsan-tech-18a27',
    storageBucket: 'ihsan-tech-18a27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrdzQtROWMs6QPDpzGqeSFnIILvbvxcp4',
    appId: '1:317504441577:ios:fab7a42832b2c27a027478',
    messagingSenderId: '317504441577',
    projectId: 'ihsan-tech-18a27',
    storageBucket: 'ihsan-tech-18a27.appspot.com',
    iosBundleId: 'com.ihsantech.ihsantech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrdzQtROWMs6QPDpzGqeSFnIILvbvxcp4',
    appId: '1:317504441577:ios:fab7a42832b2c27a027478',
    messagingSenderId: '317504441577',
    projectId: 'ihsan-tech-18a27',
    storageBucket: 'ihsan-tech-18a27.appspot.com',
    iosBundleId: 'com.ihsantech.ihsantech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NBhsxDpQJl7yyK6f5f8jFIWIFiVO7SA',
    appId: '1:317504441577:web:818e23780a1df395027478',
    messagingSenderId: '317504441577',
    projectId: 'ihsan-tech-18a27',
    authDomain: 'ihsan-tech-18a27.firebaseapp.com',
    storageBucket: 'ihsan-tech-18a27.appspot.com',
    measurementId: 'G-59JVL48BCP',
  );
}
